### ISSUE TITLE
Heyyy hiii , am trying to build a radio app using the assets_audio_player flutter package and am not able to play music , can u please help me ?

### ISSUE THREAD

**Issue by ampro88** [Gairik-Shandilya/Xylophone--Flutter#1]

**Comment by Gairik-Shandilya** [comment]
can you show me your repo or the snippet of the pubsec.yaml where you imported the package and implemented it.

IN YOUR PUBSEC.YAML ADD THIS

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/

IN YOUR MAIN.DART

import 'package:audioplayers/audioplayers.dart';  

WITHIN YOUR CLASS STATE ADD THIS BEFORE @override

  AudioPlayer audioPlayer = AudioPlayer();

WITHIN YOUR BUTTON USE THIS

onPressed: () async {
          await audioPlayer.play(AssetSource("Your sound file address"));
        },
ps : make sure to keep your audio file in  assets/audio/

**Comment by Gairik-Shandilya** [comment]
I suggested a way of adding audio assets to your app . Did you try working
on it? If it doesn't work then tell me I will see what I can do and let you
know. We can have a Google meet and get it done. Waiting for ur reply over
here or on github.

**Comment by ampro88** [comment]
In my use case am having a list of 20 radios needed to be played with next and previous buttons , I dont how to do them , ur method is suitable for single radio player . 

Am still in the beginning phase of my app bro , do u have discord or google meet ? so I can share my screen and explain ?

**Comment by Gairik-Shandilya** [comment]
Yes feel free to contact me on discord - (Gairik#8152)
Will try my best to help you out

**Comment by ampro88** [comment]
I requested in discord
